language: java
sudo: false
jdk:
  - openjdk7
  - openjdk8

before_install:
  - chmod +x ./scripts/check_pk_health.sh
script:
  - sudo ./scripts/check_pk_health.sh

addons:
  apt:
    packages:
      - python3
      - python3-pip
